### PR TITLE
Some_changes & suggestions

### PR DESCRIPTION
**Pull request by PARTHIB-DEB**
Few little changes for betterment !!

### CODE REVIEW

**Comment by Sambit003** [comment]
Can you make the changes in master_experimental branch ?

**Comment by Sambit003** [comment]
@PARTHIB-DEB Can you make the changes in "master_experimental" branch ?

**Comment by PARTHIB-DEB** [comment]
Then it will be a new branch , ok apprently merge the code and then make a new branch 😄 😄

**Comment by Sambit003** [comment]
@PARTHIB-DEB for the time beings, I'm closing this PR without merging into code base. you make a separate branch and then make the necessary changes the make the branch push here.

**Pull request closed without merging**
